### ISSUE TITLE
Long Url limited to 140 characters

### ISSUE THREAD

**Issue by julienmarie** [pibico/pibicut#1]
If submitting a (really) long url, it won't work:

```Shortener iDzEe: 'Long URL' (https://erp.xxxxxxx.com/integrations/stripe_checkout?amount=2222.0&title=ChateauMarie+Digital+Ventures+Philippines+Inc.&description=Credit+Card+Payment+Request+for+ACC-SINV-2022-00014&reference_doctype=Payment+Request&reference_docname=ACC-PRQ-2022-00013&payer_email=jm%2B1%40producture.com&payer_name=Arnold+Schwartzenneger&order_id=ACC-PRQ-2022-00013&currency=PHP) will get truncated, as max characters allowed is 140```

Is there a way to fix it ?

Thank you

**Comment by pibico** [comment]
I have just modified in the Shortener Doctype, the fieldtype for fieldname long_url, from Data (maximum length allowed 140 chars) for Text. Please reinstall the app
